language: node_js
node_js:
  - 'v10.16.0'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - yarn install

script:
  - echo "Skipping tests"
  - yarn run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  fqdn: nadeshikokaruta.com
  local_dir: dist
  keep_history: true
  on:
    branch: master
